### ISSUE TITLE
Highlight Pandoc style citations 

### ISSUE THREAD

**Issue by phlind** [MalignantCarp/obsidian-typography-plugin#4]
I'm not sure if this is in the scope of the plugin, but would it be possible to also target Pandoc style citations and highlight them?

Like `[@Citekey, 100]`, `[See @Citekey, 100--120]`, `[@Citekey]` etc.

**Comment by MalignantCarp** [comment]
No, not really in the scope of the plugin. I perused Pandoc's code and couldn't really spot where any tagging would occur, so I'm not really sure if there's a quick way to achieve what you're looking for with just CSS, so unfortunately can't help there. Looking at Pandoc's issues, it looks like it's possibly not being maintained anymore, but there does appear to be a fork with some recent activity and it could be worth looking into as that might give you some options: https://github.com/BumbrT/obsidian-html-export (reference here: https://github.com/OliverBalfour/obsidian-pandoc/issues/88)

**Comment by phlind** [comment]
I see, probably it's not possible anyway because you can't really target the citation keys. They are not dependant on the Obsidian plugin for pandoc though, they are just pandoc syntax.
