### ISSUE TITLE
Style settings don't appear

### ISSUE THREAD

**Issue by phlind** [MalignantCarp/obsidian-typography-plugin#5]
Hey, the settings for the plugin don't appear in the Style Settings panel for me.

**Comment by MalignantCarp** [comment]
I've noticed some oddities going on with Style Settings. I'm not sure if it is my plugin or Style Settings, but now that someone else has experienced it, I will look into it further. Let me know if disabling and re-enabling Style Settings makes it appear for you.

**Comment by phlind** [comment]
Oh yes, disabling and enabling it again fixed it. Thanks!

**Comment by MalignantCarp** [comment]
At least that's a workaround. The fun part is getting this bug to replicate, as it does not always occur. I think I know what's causing it, but until I can get the settings to go missing again, I can't test to see if I'm right. 🤣

**Comment by MalignantCarp** [comment]
I haven't seen this issue in a while, so hopefully my fix corrected whatever was causing it (or Style Settings itself got an update that fixed it). At any rate, if you see the issue again, feel free to re-report.
