### ISSUE TITLE
Tag + link bug

### ISSUE THREAD

**Issue by phlind** [MalignantCarp/obsidian-typography-plugin#8]
While I'm at it, another bug. When the previous line contains a #tag and the line with the quotation contains a link after the quotation, it won't work. Yes, a rather special case, but still. Reproducable with:

```
#tag
Something "something" and a [[Link]].
```

If you remove either the #tag or the link, it works.

**Comment by MalignantCarp** [comment]
This should be fixed in 0.0.6. Please let me know if it is resolved for you and I will close this issue.

**Comment by MalignantCarp** [comment]
This seems to be fixed.
