### ISSUE TITLE
Transclusions/embeds are destroyed on Obsidian v0.13.14 (only)

### ISSUE THREAD

**Issue by MalignantCarp** [MalignantCarp/obsidian-typography-plugin#9]
Not entirely certain how this is a thing, but it appears that embeds/transclusions no longer function in the most recent Obsidian release when this plugin is working.

At present, we pass the HTML element to the typography routine, which runs modifications on the innerHTML of that element. It then returns that innerHTML and we replace that element's innerHTML with the modified innerHTML.

If we immediately return the innerHTML unmodified, it is still a problem, so it is not the modification that is the problem. I am guessing something is going on with the innerHTML now that did not happen in previous versions of Obsidian. If we do not set the innerHTML of the element with the modifications, the transclusion will appear as expected. Not sure if it is sanitization of some kind or what.

The good news is, in newer builds, we now traverse the DOM and make modifications directly to the textContent only of the respective textNodes. However, it is proving difficult to re-establish highlighting while functioning this way. I can push an update immediately that will fix this bug, but will eliminate highlighting.

**Comment by MalignantCarp** [comment]
And for some reason, the occasional task is duplicated as a regular list item. Not sure how/why that is happening, either. Possibly a bug with Obsidian.

**Comment by phlind** [comment]
Transclusions of other notes are working for me, but queries don't, they just show the loading animation (in Live Preview mod they do work, just not in Reading mode). I am not sure if you mean the same.

**Comment by MalignantCarp** [comment]
Interesting. See, this is what I get with the plugin on:

![image](https://user-images.githubusercontent.com/93364935/147422911-2eb520c8-4fb2-4598-be17-8a69745938d4.png)

And what it is supposed to appear as (with the plugin off and the page reloaded):

![image](https://user-images.githubusercontent.com/93364935/147422965-78ab8b24-7ac9-44fd-be99-490dab2b7b1a.png)

I am assuming now that if transclusions are working for you, that there must be another plugin that is combining with mine and causing this trouble. I don't suppose you'd mind dropping the list of plugins you have enabled? If I can subtract those from list of 45 that could help me figure out the combination much faster. Although I am rebuilding the plugin to deal only in the DOM without replacing HTML wholesale, in the event I ever do need to handle setting innerHTML, it would be nice for it to work as expected. Something is causing trouble, as when I just get and set the innerHTML rather than doing any of my processing, it all breaks, too.

**Comment by phlind** [comment]
Reading Mode:
![Bildschirmfoto 2021-12-27 um 10 30 23](https://user-images.githubusercontent.com/30386310/147457707-f6d4d3f8-0bbd-4642-958d-30316b32806b.png)


Live Preview:
![Bildschirmfoto 2021-12-27 um 10 28 05](https://user-images.githubusercontent.com/30386310/147457531-d69e8ed0-291f-4c93-bb32-0934f0e0910f.png)

Here is the list of plugins I have:

```
better-fn
better-word-count
block-reference-count
cross-reference-navigation
customizable-sidebar
darlal-switcher-plus
dataview
get-info-plugin
graph-analysis
hotkey-helper
longform
map-of-content
metadata-extractor
mrj-add-codemirror-matchbrackets
mysnippets-plugin
note-refactor-obsidian
obsidian-admonition
obsidian-advanced-uri
obsidian-citation-plugin
obsidian-copy-block-link
obsidian-daily-stats
obsidian-hider
obsidian-icon-folder
obsidian-journey-plugin
obsidian-kanban
obsidian-languagetool-plugin
obsidian-native-scrollbars
obsidian-show-file-path
obsidian-stille
obsidian-style-settings
obsidian-tabout
obsidian-timeline
obsidian-typography-plugin
obsidian-vimrc-support
obsidian42-brat
plugin-changelogs
supercharged-links-obsidian
tabout
tag-page-preview
various-complements

```

**Comment by MalignantCarp** [comment]
Ah perfect. Your screenshot showed a different Obsidian version. Upgrading to insider build v0.13.16 fixed this, so it was clearly an Obsidian bug in 0.13.14 that has since been fixed.
